name: Generate Documentation
on:
  push:
    branches:
      - 'feature/remove-bootstrap-dep'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Build Docs
        env:
          NODE_ENV: 'production'
          ASSET_PREFIX: '/react-generated-form'
        run: |
          cd docs
          yarn
          yarn build
          yarn export

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './docs/out'
