name: Build / Publish (NPM) / Deploy
on:
  pull_request:
  push:
    paths:
      - 'src/*'
    branches:
      - 'master'
      - 'develop'
      - 'f/*'
      - 'h/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'

    - name: 'Install Dependencies'
      id: install
      run: yarn

    - name: 'Run tests suites'
      id: test
      run: yarn test
      continue-on-error: true

    - name: 'Build Project'
      id: build
      run: yarn build

    - name: 'Set git identity'
      id: git-identity
      run: |
        git config user.email "$GTHUB_ACTOR@users.noreply.github.com"
        git config user.name "$GITHUB_ACTOR"

    - name: 'Bump package version'
      id: package-version
      continue-on-error: true
      run: |
        if [[ $GITHUB_REF == refs/heads/* ]]; then
          REF=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
        elif [[ $GITHUB_REF == refs/pull/* ]]; then
          REF=pr-${{ github.event.number }}
        fi

        if [[ $REF == master ]]; then
          VERSION=$(npm version patch)
        else
          VERSION=$(npm version prerelease --preid="$REF")
        fi

        echo "::set-output name=version::${VERSION}"

    - name: 'Release Stable'
      if: ${{ github.ref == 'refs/heads/master' }}
      run: npm publish --tag latest
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: 'Canary'
      if: ${{ github.ref == 'refs/heads/develop' }}
      run: npm publish --tag canary
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: 'Dev Release'
      if: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop' }}
      run: npm publish --tag next
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: 'Push TAGS and Version'
      run: |
        git push -u origin ${GITHUB_REF#refs/heads/}
        git push --tags
  deploy-docs:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Build Docs
        env:
          ASSET_PREFIX: '/react-generated-form'
        run: |
          cd docs
          yarn add react-generated-form@${{ needs.build.outputs.version }}
          yarn build
          yarn export

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './docs/out'
