name: Publish to NPM
on:
  pull_request:
  push:
    branches:
      - 'develop'
      - 'f/*'
      - 'h/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Set git identity'
      id: git-identity
      run: |
        git switch -c 'master'
        git config user.email "$GTHUB_ACTOR@gusers.noreply.github.com"
        git config user.name "$GITHUB_ACTOR"

    - name: 'Update package version'
      id: package-version
      run: |
        if [[ $GITHUB_REF == refs/heads/* ]]; then
          REF=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
        elif [[ $GITHUB_REF == refs/pull/* ]]; then
          REF=pr-${{ github.event.number }}
        fi

        if [[ $REF == develop ]]; then
          npm version patch -m 'version bump'
        else
          npm version prerelease --preid="$REF" -m 'version bump'
        fi

        git push -u origin ${GITHUB_REF#refs/heads/}
        git push --tags

    # - uses: actions/setup-node@v2
    #   with:
    #     node-version: '12.x'

    # - name: Install Dependencies
    #   id: install
    #   run: yarn

    # - name: Run tests suites
    #   id: test
    #   run: yarn test

    # - name: Build Project
    #   id: build
    #   run: yarn build
