name: Publish to NPM
on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'f/*'
      - 'h/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'

    - name: 'Install Dependencies'
      id: install
      run: yarn

    - name: 'Run tests suites'
      id: test
      run: yarn test
      continue-on-error: true

    - name: 'Build Project'
      id: build
      run: yarn build

    - name: 'Set git identity'
      id: git-identity
      run: |
        git config user.email "$GTHUB_ACTOR@gusers.noreply.github.com"
        git config user.name "$GITHUB_ACTOR"

    - name: 'Bump package version'
      if: ${{ github.ref != 'refs/heads/master' }}
      id: package-version
      continue-on-error: true
      run: |
        if [[ $GITHUB_REF == refs/heads/* ]]; then
          REF=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
        elif [[ $GITHUB_REF == refs/pull/* ]]; then
          REF=pr-${{ github.event.number }}
        fi

        if [[ $REF == master ]]; then
          npm version patch
        else
          npm version prerelease --preid="$REF"
        fi

    - name: 'Release Stable'
      if: ${{ github.ref == 'refs/heads/master' }}
      run: npm publish --tag stable
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: 'Canary'
      if: ${{ github.ref == 'refs/heads/develop' }}
      run: npm publish --tag canary
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: 'Dev Release'
      if: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop' }}
      run: npm publish --tag dev
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: 'Push TAGS and Version'
      run: |
        git push -u origin ${GITHUB_REF#refs/heads/}
        git push --tags
